export { NavbarComponent } from './navbar/navbar.component'
export { LoginFormComponent } from './login-form/login-form.component'
export { HomeComponent } from './home/home.component'
export { GalleriesComponent } from './galleries/galleries.component'
export { DuelsComponent } from './duels/duels.component'